# Generated by Django 5.0.6 on 2024-06-16 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
