# Generated by Django 5.0.6 on 2024-06-15 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_dev', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
